<?php

namespace AppBundle\Repository;

/**
 * VdmPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdmPostRepository extends \Doctrine\ORM\EntityRepository
{
}
